### ISSUE TITLE
Where is this code base? Is this not open for updates?

### ISSUE THREAD

**Issue by ghost** [structuremap/StructureMap.Web#1]
Repo is empty however there are several other libs that are dependent on this lib.

**Comment by jeremydmiller** [comment]
This code is in the 3.1 branch of the main StructureMap repo. See https://github.com/structuremap/structuremap/tree/3.1/src.

Nothing in this lib has changed in a couple years, and I think of it as obsolete anyway.

**Comment by ghost** [comment]
Ah. Thank you. The StructureMap.MVC5 (and the .Update... maybe) nuget package depends on this lib which hasn't been updated in awhile.

Those implementations call the HttpContextLifecycle static class as shown below in their implementation of a StructureMapScopeModule

```
context.EndRequest += (sender, e) => {
    HttpContextLifecycle.DisposeAndClearAll();
    ...
};
```
Is there a recommended lib we should be pulling the HttpContextLifecycle from?
